version: 2
jobs:
  build:
    docker:
        - image: trzeci/emscripten:sdk-incoming-64bit

    steps:
      - checkout

      - run:
          name: Prebuild
          command: |
            git submodule init
            git submodule update --remote
            npm install

      - run:
          name: Build
          command: npm run build

      - run:
          name: Test
          command: npm run test
