version: 2
jobs:
  build:
    docker:
        - image: trzeci/emscripten:sdk-incoming-64bit

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Prebuild
          command: |
            git submodule init
            git submodule update --remote
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: npm run build

      - run:
          name: Test
          command: npm run test
